// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUemIN-XkCe5rIiczsRZGG84BRJiMUW-Q',
    appId: '1:794959026077:web:6c66f61285d77099394174',
    messagingSenderId: '794959026077',
    projectId: 'mediassure218',
    authDomain: 'mediassure218.firebaseapp.com',
    storageBucket: 'mediassure218.firebasestorage.app',
    measurementId: 'G-TDTWC97JQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNS3zW4pDQX3-a6bxeoG5PBylsGijVeHM',
    appId: '1:794959026077:android:e2edec951dffbabe394174',
    messagingSenderId: '794959026077',
    projectId: 'mediassure218',
    storageBucket: 'mediassure218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuBbcB9IzuVj3JW64_lMvP76ozHgcJCqs',
    appId: '1:794959026077:ios:f29e9e0d2cd2d0c7394174',
    messagingSenderId: '794959026077',
    projectId: 'mediassure218',
    storageBucket: 'mediassure218.firebasestorage.app',
    iosBundleId: 'com.example.mediassure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuBbcB9IzuVj3JW64_lMvP76ozHgcJCqs',
    appId: '1:794959026077:ios:f29e9e0d2cd2d0c7394174',
    messagingSenderId: '794959026077',
    projectId: 'mediassure218',
    storageBucket: 'mediassure218.firebasestorage.app',
    iosBundleId: 'com.example.mediassure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUemIN-XkCe5rIiczsRZGG84BRJiMUW-Q',
    appId: '1:794959026077:web:fe0f9e557adc9f27394174',
    messagingSenderId: '794959026077',
    projectId: 'mediassure218',
    authDomain: 'mediassure218.firebaseapp.com',
    storageBucket: 'mediassure218.firebasestorage.app',
    measurementId: 'G-CGC030YHV7',
  );
}
